name: Upload template and staging files to Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing python packages
      run: |
        pip install -e .

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set GCP project
      run: |
        gcloud config set project curso-apache-beam-gcp

    - name: Creating template
      run: |
        python main.py \
            --setup_file="./setup.py" \
            --runner="DataflowRunner" \
            --project="curso-apache-beam-gcp" \
            --region="us-central1" \
            --temp_location="gs://curso-apache-beam-gcp-n/temp" \
            --staging_location="gs://curso-apache-beam-gcp-n/staging" \
            --template_location="gs://curso-apache-beam-gcp-n/template/postgres-mongodb-to-bq" \
            --save_main_session

