name: Upload template and staging files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing package
      run: |
        pip install -e .

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set GCP project
      run: |
        gcloud config set project curso-apache-beam-gcp

    - name: Creating template
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        GCP_STORAGE_BUCKET_TEMP: ${{ secrets.GCP_STORAGE_BUCKET_TEMP }}
        GCP_STORAGE_BUCKET_STAGING: ${{ secrets.GCP_STORAGE_BUCKET_STAGING }}
        GCP_STORAGE_BUCKET_TEMPLATE: ${{ secrets.GCP_STORAGE_BUCKET_TEMPLATE }}
        GCP_STORAGE_BUCKET_REGION: ${{ secrets.GCP_STORAGE_BUCKET_REGION }}
        GCP_BIGQUERY_TABLES: ${{ secrets.GCP_BIGQUERY_TABLES }}
        GCP_SECRET_ID: ${{ secrets.GCP_BIGQUERY_TABLES }}

      run: |
        python main.py \
            --setup_file="./setup.py" \
            --runner="DataflowRunner" \
            --project="$GOOGLE_CLOUD_PROJECT" \
            --region="$GCP_STORAGE_BUCKET_REGION" \
            --temp_location="$GCP_STORAGE_BUCKET_TEMP" \
            --staging_location="$GCP_STORAGE_BUCKET_STAGING" \
            --template_location="$GCP_STORAGE_BUCKET_TEMPLATE" \
            --save_main_session
